import Header from "@/components/Header";
import PrivateRoute from "@/components/PrivateRoute";
import { PWC } from "@/types/components";

export const metadata = {
  title: "Service",
  description: "Generated by create next app"
};

const ServiceLayout = ({ children }: PWC) => (
  <PrivateRoute>{children}</PrivateRoute>
);

export default ServiceLayout;
