import { Inter } from "next/font/google";
import Providers from "./Providers";
import "./globals.css";
import { PWC } from "@/types/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mint dApp",
  description: "Generated by create next app"
};

function RootLayout({ children }: PWC) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

export default RootLayout;
