import { Inter } from "next/font/google";
import Providers from "./Providers";
import "./globals.css";
import { PWC } from "@/types/components";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FR3ELA",
  description: "Generated by create next app"
};

function RootLayout({ children }: PWC) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
