import Header from "@/components/Header";
import PrivateRoute from "@/components/PrivateRoute";
import { PWC } from "@/types/components";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app"
};

function DashboardLayout({ children }: PWC) {
  return (
    <PrivateRoute>
      <Header />
      {children}
    </PrivateRoute>
  );
}

export default DashboardLayout;
