import Banner from "@/components/Banner";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import PrivateRoute from "@/components/PrivateRoute";
import { ArrowRightIcon } from "@heroicons/react/24/solid";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <PrivateRoute>
        <Header />
        {children}
      </PrivateRoute>
    </>
  );
}
